version: 0.2
phases:
  pre_build:
    commands:
      - echo installing application dependencies...
      - npm install
  build:
    commands:
      - echo creating a build bundle...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'