version: 1.0

phases:
  pre_build:
    commands:
      - npm install
      - echo installing application dependencies...
  build:
    commands:
      - npm run build
      - echo creating a build file...

artifacts:
  type: zip
  paths:
    - './build/**/*'

cache:
  paths:
    - './node_modules/**/*'
