export const commonTeams = [
    { label: 'BI ', value: 1 },
    { label: 'Big Data ', value: 2 },
    { label: 'Block Chain ', value: 3 },
    { label: 'BPM ', value: 4 },
    { label: 'BPO ', value: 5 },
    { label: 'Data Science ', value: 6 },
    { label: 'Delivery ', value: 7 },
    { label: 'Java ', value: 8 },
    { label: 'Microsoft ', value: 9 },
    { label: 'Mobility ', value: 10 },
    { label: 'Open Source ', value: 11 },
    { label: 'Oracle ', value: 12 },
    { label: 'Pega ', value: 13 },
    { label: 'QA ', value: 14 },
    { label: 'RPA ', value: 15 },
    { label: 'Sales Force ', value: 16 },
    { label: 'Service Now ', value: 17 },
    { label: 'Support ', value: 18 },
    { label: 'UI ', value: 19 },
    { label: 'Other', value: 20 },
]

